### ISSUE TITLE
2019/05/07

### ISSUE THREAD

**Issue by chez-shanpu** [StudioAquatan/TechTalkTuesday#21]
前回 #20

**Comment by taxio** [comment]
Goで話したいトピックが結構溜まってる
- オプション引数
  - https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html
- xerrors
  - https://godoc.org/golang.org/x/xerrors
  - https://go.googlesource.com/proposal/+/master/design/29934-error-values.md
- ~~tinygo~~
- call graph
  - https://github.com/TrueFurby/go-callvis
  - https://godoc.org/golang.org/x/tools/go/callgraph

**Comment by chez-shanpu** [comment]
monorepoというソースコードの管理方法について，対称的な見解を述べた二つの記事がある．この記事を読みながら，みんなでコードの管理方法について考えてみたい．

https://medium.com/@adamhjk/monorepo-please-do-3657e08a4b70
https://medium.com/@mattklein123/monorepos-please-dont-e9a279be011b

**Comment by tjmtmmnk** [comment]
ブロックチェーンを用いたクラウドストレージサービスのstorjのアルゴリズムを紹介してみる
- https://medium.com/@braydonf/how-files-are-encrypted-encoded-and-concurrently-transferred-peer-to-peer-on-the-storj-network-3910643c89f4
- https://storj.io/whitepaper/
- https://github.com/storj/storj
- [リードソロモン符号](https://www.jstage.jst.go.jp/article/itej/70/7/70_571/_pdf)
- [BIP39(Mnemonic)](https://tech.bitbank.cc/about-bip39/)
- https://qiita.com/smatsui@github/items/41af7a779e8209286a71

**Comment by pddg** [comment]
Datastoreが生まれ変わった
https://cloud.google.com/datastore/docs/firestore-or-datastore?hl=ja
